main:
    -
        class: first
        path: homepage
        title: 'This is the first menu item.'
        label: Home
    -
        path: entry/1
        label: 'Second item'
        submenu:
            -
                path: entry/2
                label: 'Sub 1'
            -
                path: entry/3
                class: menu-item-class
                label: 'Sub 2'
            -
                path: entry/4
                label: 'Sub 3'
    -
        path: pages/
        label: 'All pages'
    -
        class: last
        link: 'http://bolt.cm'
        label: 'The Bolt site'
